app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::get('showassets', function () {
    return link_to_asset('/css/app.css');
});

Route::get('show_first_photo', function () {
    return dd(url(App\Flyer::find(1)->photos()->first()->path));
});







/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //home, about and contact pages
    Route::get('/', [
        'as' => 'home_path',
        'uses' => 'PagesController@index'
    ]);
    
    Route::get('about', [
        'as' => 'about_path',
        'uses' => 'PagesController@about'
    ]);

    Route::get('contact', [
        'as' => 'contact_path',
        'uses' => 'PagesController@contact'
    ]);

    

    //profile pages
    Route::get('users/profile', 'PagesController@profile');
    Route::get('users/profile/my-flyers', 'FlyersController@indexUserFlyers');

    //routes of flyers
    Route::resource('flyers', 'FlyersController');
    //Route::get('{zip}/{street}', 'FlyersController@show');
	Route::post('{flyerId}/photos', 'PhotosController@store');

    // Authentication Routes...
    Route::auth();
    
    
    
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
    * Check if this user owns the flyer
    *
    * $param App\Flyer a flyer object
    * $return boolean
    */
    public function owns($relation){
        return $relation->user_id == $this->id;
    }

    /**
     * Represent the one-to-many relationship between App\User and App\Flyer
     * 
     * @return hasMany
     */
    public function flyers(){
        return $this->hasMany('App\Flyer');
    }

    /**
     *  save a flyer object via this user
     *
     * @param App\Flyer a new flyer object
     * @return App\Flyer
     */
    public function publish(Flyer $flyer){
        return $this->flyers()->save($flyer);
    }
}

resources/views/users/profile.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                    <div class="panel-body">
                        You are logged in!
                    </div>
                    <br><br>
                    <p>
                        {!!link_to_route('flyers.index', 'view latest flyers', null, ['class' => 'btn btn-success btn-lg'])!!}
                        <a href="{{url('users/profile/my-flyers')}}" class="btn btn-success btn-lg">your own flyers</a>
                        {!!link_to_route('flyers.create', 'create a new flyer', null, ['class' => 'btn btn-success btn-lg'])!!}
                    </p>

            </div>
        </div>
    </div>
</div>
@endsection